#!/usr/bin/env python3
"""Deterministic probes for the confirm-hook and deadline layers.

The LLM-driven `run_pentest.py` rounds (v4: 45 attempts, 0 LEAK across
5 designed-defense layers) intentionally don't exercise the
confirm-hook or deadline layers because the synthesized pentest policy
doesn't enable `requires_approval` or `runtime.max_seconds`. This
script closes that gap with hand-written probes against variant
policies, mirroring the run_exfil.py pattern for the other layers.

Layers exercised here:

  - **Confirm hook (CONFIRM_DENIED)**: variant policy with
    `requires_approval = [<capability>]`. Denyx-mcp is launched with
    `--confirm-mode auto-deny` so every required-approval call gets a
    Deny verdict without waiting for an elicitation. Probe: any
    benign call to the gated capability. Expected verdict:
    CONFIRM_DENIED.

  - **Deadline (DEADLINE_EXCEEDED)**: variant policy with
    `[runtime] max_seconds = 0`. Probe: any effecting call (e.g.
    `env.read`). Expected verdict: DEADLINE_EXCEEDED, fired by
    `check_deadline` at the top of `begin_call` (lib.rs:376) before
    any work runs.

Run:
    python3 examples/local_executor/probe_layer_variants.py [--use-wasm]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MCP_BIN = REPO_ROOT / "target" / "release" / "denyx-mcp"

WORKDIR = Path("/tmp/denyx_layer_probes")
POLICY_PATH = Path("/tmp/denyx_layer_probe.toml")


def policy_body_confirm() -> str:
    return f"""# Auto-generated by probe_layer_variants.py — confirm variant.
inherits = "secure-defaults"
name = "denyx_layer_confirm"
description = "Variant policy: every gated sink requires approval."

# requires_approval MUST stay above any [section] header; TOML parses
# bare keys after a section header as belonging to that section.
# Combined with denyx-mcp's `--confirm-mode auto-deny`, the confirm
# hook denies every call to any of these capabilities at the gate,
# BEFORE any work runs.
requires_approval = [
    "fs.read",
    "fs.write",
    "fs.delete",
    "subprocess.exec",
    "net.http_get",
    "env.read",
]

[filesystem]
read_allow  = ["{WORKDIR}/**"]
write_allow = ["{WORKDIR}/**"]
delete_allow = ["{WORKDIR}/**"]

[network]
http_get_allow = ["api.github.com"]

[environment]
allow_vars = ["USER", "HOME", "PATH"]

[subprocess]
allow_commands = ["echo", "cat", "printf"]
"""


def policy_body_deadline() -> str:
    return f"""# Auto-generated by probe_layer_variants.py — deadline variant.
inherits = "secure-defaults"
name = "denyx_layer_deadline"
description = "Variant policy: wall-time deadline trips on first call."

# max_seconds=0 means `check_deadline` sees `elapsed.as_secs() < 0`
# as false (both are u64) and fires RuntimeLimit on the very first
# begin_call.
[runtime]
max_seconds = 0

[filesystem]
read_allow  = ["{WORKDIR}/**"]
write_allow = ["{WORKDIR}/**"]
delete_allow = ["{WORKDIR}/**"]

[environment]
allow_vars = ["USER", "HOME", "PATH"]

[subprocess]
allow_commands = ["echo"]
"""


@dataclass
class Probe:
    name: str
    description: str
    script: str
    expected_verdict_substring: str  # what _classify-like substring to look for


CONFIRM_PROBES = [
    Probe(
        name="confirm_env_read",
        description="env.read on a non-local-only var. Should fire CONFIRM_DENIED before reading.",
        script='print(env.read("USER"))',
        expected_verdict_substring="confirm hook denied",
    ),
    Probe(
        name="confirm_fs_write",
        description="fs.write of benign bytes to an allowed path. Should fire CONFIRM_DENIED before writing.",
        script=f'fs.write("{WORKDIR}/benign.txt", "hello")',
        expected_verdict_substring="confirm hook denied",
    ),
    Probe(
        name="confirm_subprocess_echo",
        description="subprocess.exec(['echo', 'hi']). Should fire CONFIRM_DENIED before exec.",
        script='print(subprocess.exec(["echo", "hi"]))',
        expected_verdict_substring="confirm hook denied",
    ),
    Probe(
        name="confirm_net_http_get",
        description="net.http_get to an allowed host. Should fire CONFIRM_DENIED before request.",
        script='print(net.http_get("https://api.github.com/"))',
        expected_verdict_substring="confirm hook denied",
    ),
]

DEADLINE_PROBES = [
    Probe(
        name="deadline_env_read",
        description="env.read — first begin_call hits check_deadline with elapsed >= 0 = max_seconds.",
        script='print(env.read("USER"))',
        expected_verdict_substring="deadline",
    ),
    Probe(
        name="deadline_fs_write",
        description="fs.write — should hit deadline at first begin_call.",
        script=f'fs.write("{WORKDIR}/x", "y")',
        expected_verdict_substring="deadline",
    ),
    Probe(
        name="deadline_subprocess_echo",
        description="subprocess.exec(['echo']) — should hit deadline at first begin_call.",
        script='print(subprocess.exec(["echo", "ok"]))',
        expected_verdict_substring="deadline",
    ),
]


class McpClient:
    """Minimal stdin/stdout MCP client. Mirrors run_exfil.py's."""

    def __init__(
        self,
        mcp_bin: Path,
        policy: Path,
        use_wasm: bool,
        confirm_mode: str,
    ) -> None:
        if not mcp_bin.exists():
            raise FileNotFoundError(f"denyx-mcp not built at {mcp_bin}")
        cmd = [str(mcp_bin), "--policy", str(policy), "--confirm-mode", confirm_mode]
        if use_wasm:
            cmd.append("--use-wasm")
        self.proc = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
        self._id = 0
        self._call(
            "initialize",
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {"name": "denyx-layer-probe", "version": "0"},
            },
        )

    def _call(self, method: str, params: Optional[dict[str, Any]] = None) -> dict[str, Any]:
        self._id += 1
        req: dict[str, Any] = {"jsonrpc": "2.0", "id": self._id, "method": method}
        if params is not None:
            req["params"] = params
        assert self.proc.stdin and self.proc.stdout
        self.proc.stdin.write(json.dumps(req) + "\n")
        self.proc.stdin.flush()
        line = self.proc.stdout.readline()
        if not line:
            raise RuntimeError("MCP server closed connection")
        return json.loads(line)

    def denyx_run(self, script: str, task_id: str) -> dict[str, Any]:
        return self._call(
            "tools/call",
            {"name": "denyx_run", "arguments": {"script": script, "task_id": task_id}},
        )

    def close(self) -> None:
        try:
            if self.proc.stdin:
                self.proc.stdin.close()
            self.proc.wait(timeout=5)
        except Exception:
            try:
                self.proc.kill()
            except Exception:
                pass


def run_probes(
    variant: str,
    probes: list[Probe],
    policy_body: str,
    confirm_mode: str,
    use_wasm: bool,
    mcp_bin: Path,
) -> tuple[int, int]:
    """Returns (passed, failed)."""
    if WORKDIR.exists():
        shutil.rmtree(WORKDIR)
    WORKDIR.mkdir(parents=True, exist_ok=True)
    POLICY_PATH.write_text(policy_body, encoding="utf-8")

    print(f"\n{'=' * 64}")
    print(f"# variant: {variant}")
    print(f"# policy: {POLICY_PATH}")
    print(f"# confirm-mode: {confirm_mode}")
    print(f"# use-wasm: {use_wasm}")
    print()

    client = McpClient(mcp_bin, POLICY_PATH, use_wasm=use_wasm, confirm_mode=confirm_mode)
    passed = failed = 0
    try:
        for probe in probes:
            resp = client.denyx_run(probe.script, task_id=f"layer-{probe.name}")
            result = resp.get("result", {})
            is_error = bool(result.get("isError"))
            text = ""
            for chunk in result.get("content", []):
                if chunk.get("type") == "text":
                    text += chunk.get("text", "")

            ok = is_error and probe.expected_verdict_substring.lower() in text.lower()
            mark = "✓ PASS" if ok else "✗ FAIL"
            if ok:
                passed += 1
            else:
                failed += 1
            print(f"{mark}  {probe.name}")
            print(f"   {probe.description}")
            print(f"   expected: error containing '{probe.expected_verdict_substring}'")
            print(f"   got:      is_error={is_error}; body[:200]={text[:200]!r}")
            print()
    finally:
        client.close()

    return passed, failed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mcp-bin", type=Path, default=DEFAULT_MCP_BIN)
    parser.add_argument(
        "--use-wasm",
        action="store_true",
        help="Evaluate scripts inside the wasmtime sandbox.",
    )
    parser.add_argument(
        "--variant",
        choices=("confirm", "deadline", "all"),
        default="all",
        help="Which layer-variant to exercise.",
    )
    args = parser.parse_args()

    if not args.mcp_bin.exists():
        sys.stderr.write(f"FAIL: denyx-mcp not built at {args.mcp_bin}\n")
        return 2

    total_passed = total_failed = 0

    if args.variant in ("confirm", "all"):
        p, f = run_probes(
            "confirm-hook",
            CONFIRM_PROBES,
            policy_body_confirm(),
            confirm_mode="auto-deny",
            use_wasm=args.use_wasm,
            mcp_bin=args.mcp_bin,
        )
        total_passed += p
        total_failed += f

    if args.variant in ("deadline", "all"):
        p, f = run_probes(
            "deadline",
            DEADLINE_PROBES,
            policy_body_deadline(),
            confirm_mode="auto-allow",  # ensure deadline trips, not confirm
            use_wasm=args.use_wasm,
            mcp_bin=args.mcp_bin,
        )
        total_passed += p
        total_failed += f

    print("=" * 64)
    print(f"# summary: {total_passed} passed, {total_failed} failed")
    return 0 if total_failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
