//! Policy file generator. Emits a starter `denyx.toml` for a given
//! project language. Every template:
//!
//! - inherits the `secure-defaults` preset (blocks credentials, cloud
//!   metadata IPs, RFC1918, secret env vars, destructive shell commands)
//! - extends the filesystem deny list with staging/qa/production
//!   configuration files (`.env.production`, `secrets.yml`, etc.)
//! - declares git destructive operations as denied via
//!   `[subprocess.deny_args]` (`push --force`, `reset --hard`, ...)
//! - allows the typical toolchain commands for the language
//! - leaves `[network]` empty so any HTTP target is an explicit opt-in
//!
//! Templates are embedded const TOML so the generator has no runtime
//! filesystem dependency and is hermetic for tests.

use std::str::FromStr;

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Lang {
    Python,
    Node,
    Ruby,
    Rust,
    Go,
    /// Java / JVM. Allow-list covers both Maven (`mvn`, `pom.xml`,
    /// `target/`) and Gradle (`gradle`, `build.gradle*`, `build/`).
    /// Operators on one build system can prune the other; mixed-
    /// build projects (rare but real) get coverage out of the box.
    Java,
    /// .NET — `dotnet` CLI, `*.csproj` / `*.sln`, `bin/` + `obj/`.
    Dotnet,
}

impl Lang {
    pub fn name(self) -> &'static str {
        match self {
            Lang::Python => "python",
            Lang::Node => "node",
            Lang::Ruby => "ruby",
            Lang::Rust => "rust",
            Lang::Go => "go",
            Lang::Java => "java",
            Lang::Dotnet => "dotnet",
        }
    }

    pub fn template(self) -> &'static str {
        match self {
            Lang::Python => PYTHON,
            Lang::Node => NODE,
            Lang::Ruby => RUBY,
            Lang::Rust => RUST,
            Lang::Go => GO,
            Lang::Java => JAVA,
            Lang::Dotnet => DOTNET,
        }
    }
}

impl FromStr for Lang {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_lowercase().as_str() {
            "python" | "py" => Ok(Lang::Python),
            "node" | "nodejs" | "javascript" | "js" | "typescript" | "ts" => Ok(Lang::Node),
            "ruby" | "rb" | "rails" => Ok(Lang::Ruby),
            "rust" | "rs" => Ok(Lang::Rust),
            "go" | "golang" => Ok(Lang::Go),
            "java" | "kotlin" | "scala" | "jvm" | "maven" | "gradle" => Ok(Lang::Java),
            "dotnet" | "csharp" | "cs" | "fsharp" | "fs" | "vb" => Ok(Lang::Dotnet),
            other => Err(format!(
                "unknown language {other:?}; expected one of: python, node, ruby, rust, go, java, dotnet"
            )),
        }
    }
}

/// Generate a starter policy for the given language.
///
/// `permissive` selects between two polarities:
///   - `false` (default for `denyx init`): minimal write_allow.
///     `/tmp/**` is stripped so the doctor doesn't warn on the
///     starter policy by default.
///   - `true` (`denyx init --permissive`): retains the embedded
///     template verbatim, including `/tmp/**`. Less safe by
///     default, more convenient for one-off scratch work.
///
/// The distinction lives here (in the generator), not in the
/// template constants, so contributors can keep the templates
/// authored once. Stripping is purely line-based: any list-item
/// line whose trimmed form is `"/tmp/**",` (or `"/tmp/**"`) is
/// elided. TOML accepts trailing commas, so the resulting array
/// stays parseable.
pub fn generate(lang: Lang, permissive: bool) -> String {
    let raw = lang.template();
    if permissive {
        return raw.to_string();
    }
    strip_permissive_writes(raw)
}

/// Drop list-item lines whose only content is `"/tmp/**"` (with or
/// without trailing comma). Operates line-by-line so the leading
/// whitespace and trailing punctuation get cleaned together.
fn strip_permissive_writes(src: &str) -> String {
    src.lines()
        .filter(|line| {
            let t = line.trim();
            t != "\"/tmp/**\"," && t != "\"/tmp/**\""
        })
        .collect::<Vec<_>>()
        .join("\n")
        + if src.ends_with('\n') { "\n" } else { "" }
}

// Common preamble + denylists shared by every language template. Kept
// inline (not interpolated) so the generated file is human-readable
// TOML, not a templated string the user has to mentally untangle.

const PYTHON: &str = r#"# Denyx policy generated by `denyx init --lang python`.
#
# This file inherits the built-in `secure-defaults` preset, which already
# blocks: ~/.aws, ~/.ssh, .env*, /etc/passwd, RFC1918 + cloud-metadata
# IPs, AWS_*/OPENAI_API_KEY/GITHUB_TOKEN env vars, and the rm/sudo/curl/
# kubectl/aws/terraform family of commands.
#
# What this generated file ADDS on top:
#   - explicit denies on staging/qa/production config files
#   - git destructive-op denies (push --force, reset --hard, ...)
#   - Python toolchain command allowlist
#   - typical Python project source layout in read/write_allow
#
# Network is intentionally empty — opt in to specific hosts as needed.
#
# Default = minimal: the embedded `/tmp/**` write entry is STRIPPED by
# `denyx init` so the doctor doesn't warn out of the box. If your
# workflow drops scratch files under /tmp, re-run with `--permissive`
# (or add a narrower `/tmp/myproject-scratch/**` to write_allow).

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "src/**",
    "tests/**",
    "test/**",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "requirements*.txt",
    "tox.ini",
    "pytest.ini",
    ".python-version",
    "README*",
    "MANIFEST.in",
]
write_allow = [
    "src/**",
    "tests/**",
    "test/**",
    "build/**",
    "dist/**",
    ".pytest_cache/**",
    ".mypy_cache/**",
    ".ruff_cache/**",
    "/tmp/**",
]
# Belt-and-suspenders deny on staging/qa/production config artifacts.
# These supplement the preset's universal denies.
deny = [
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/production.toml",
    "**/staging.toml",
    "**/qa.toml",
    "**/production.yml",
    "**/production.yaml",
    "**/staging.yml",
    "**/staging.yaml",
    "**/qa.yml",
    "**/qa.yaml",
    "**/secrets.toml",
    "**/secrets.yml",
    "**/secrets.yaml",
]

[network]
# By default no host is reachable. Add hosts you actually need:
# http_get_allow = ["pypi.org", "files.pythonhosted.org"]

[environment]
allow_vars = ["PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL", "PYTHONPATH", "VIRTUAL_ENV"]

[subprocess]
allow_commands = [
    "python", "python3",
    "pip", "pip3", "pipx",
    "uv", "poetry", "hatch",
    "pytest", "tox",
    "mypy", "pyright",
    "ruff", "black", "isort", "flake8",
    "git",
    "make",
]
# `secure-defaults` denies the python interpreter wholesale because
# `python -c "..."` runs arbitrary code that bypasses the argv path
# gate (and thus Denyx's filesystem policy). The Python language
# template needs python to function, so we negate the deny — and
# accept the privilege grant. The deny_args below blocks the
# inline-execution flags so the agent can't trivially exfiltrate
# files via constructed paths in -c strings.
deny_commands = ["!python", "!python3"]

[subprocess.deny_args]
# Block git operations that rewrite or destroy history. The preset does
# not enforce these; project policies should.
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]
# Block inline-execution flags. `python -c "<code>"` and
# `python -e "<code>"` run arbitrary Python with full filesystem and
# network access (whatever the OS allows the user). The argv path
# gate sees the inline string but cannot reason about what the
# Python code inside it will open. Blocking the flags forces the
# agent to use real .py files, which DO go through fs.read/write
# gates.
python  = ["-c", "-e"]
python3 = ["-c", "-e"]
pip     = ["install --target", "install --prefix"]   # don't write outside venv

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv; same shape as `deny_args` above. Useful when
# you trust the binary in general but want a per-call review on
# weighty operations.
#
# Note: a pattern that overlaps a `deny_args` entry is dead code
# (deny wins). Pick patterns that pass deny_args but are still
# worth a per-call check.
#
# [subprocess.requires_approval_args]
# git  = ["push"]
# pip  = ["install --user"]
# pip3 = ["install --user"]

# Capabilities are auto-derived from the populated resource sections
# above: read_allow ⇒ fs.read, write_allow ⇒ fs.write, allow_commands
# ⇒ subprocess.exec, allow_vars ⇒ env.read, http_*_allow ⇒ net.http_*.
# Populate [network].http_get_allow to enable net.http_get, etc.

# Optional: declare a WebSearch tool with a routing hint. Bridges (the
# local-executor harness, IDE plugins, ...) read `backend_url` to tell
# the model where to make the search call instead of leaving it to
# guess. DuckDuckGo's Instant Answer API is the default — public,
# non-tracking, no auth required, returns JSON. Note: it returns
# abstracts/definitions for famous-entity queries, not full web search
# results. For broader coverage, swap for a self-hosted SearxNG,
# Brave Search, Tavily, etc. by changing the URL below and adding
# the new host to http_get_allow.
#
# [tools.WebSearch]
# capabilities   = ["net.http_get"]
# backend_url    = "https://api.duckduckgo.com/?format=json&no_html=1&skip_disambig=1&q="
# backend_method = "GET"
# description    = "DuckDuckGo Instant Answer API (public, non-tracking, JSON)."
#
# Then add to [network].http_get_allow above:
#   "api.duckduckgo.com",
"#;

const NODE: &str = r#"# Denyx policy generated by `denyx init --lang node`.
#
# Inherits `secure-defaults` (system protection baseline). Adds Node /
# TypeScript toolchain allows, project source layout, and explicit
# denies on staging/qa/production config files.
#
# Default = minimal: `denyx init` strips the embedded `/tmp/**` write
# entry. Pass `--permissive` to keep it, or add a narrower scratch
# path of your own.

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "src/**",
    "lib/**",
    "tests/**",
    "test/**",
    "__tests__/**",
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "tsconfig*.json",
    ".eslintrc*",
    ".prettierrc*",
    "vitest.config.*",
    "jest.config.*",
    "biome.json",
    "README*",
]
write_allow = [
    "src/**",
    "lib/**",
    "tests/**",
    "test/**",
    "__tests__/**",
    "dist/**",
    "build/**",
    ".next/**",
    "coverage/**",
    "/tmp/**",
]
deny = [
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/production.toml",
    "**/staging.toml",
    "**/qa.toml",
    "**/production.yml",
    "**/production.yaml",
    "**/staging.yml",
    "**/staging.yaml",
    "**/qa.yml",
    "**/qa.yaml",
    "**/secrets.json",
    "**/secrets.yml",
    "**/secrets.yaml",
]

[network]
# By default no host is reachable. Add hosts you actually need:
# http_get_allow = ["registry.npmjs.org"]

[environment]
allow_vars = ["PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL", "NODE_OPTIONS", "NPM_CONFIG_PREFIX"]

[subprocess]
allow_commands = [
    "node",
    "npm", "npx", "pnpm", "yarn",
    "tsc", "tsx", "ts-node",
    "jest", "vitest", "mocha",
    "eslint", "prettier", "biome",
    "git",
    "make",
]
# `secure-defaults` denies node + node-family interpreters because
# `node -e "<code>"` and `node -p "<expr>"` run arbitrary JS that
# bypasses the argv path gate. The Node template needs `node`, so
# we negate — and the deny_args below blocks the inline-execution
# flags. `npm`/`npx`/`tsx`/`ts-node` ultimately run node too, but
# they're project-bound (script names, package.json) and not
# generic exec surfaces.
deny_commands = ["!node"]

[subprocess.deny_args]
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]
# Block npm publish by default — it pushes to the public registry. Opt
# in by removing this entry in your project policy if you actually
# release packages from agent runs.
npm = ["publish"]
pnpm = ["publish"]
yarn = ["publish"]
# Block inline-execution flags. `node -e "<js>"` and `node -p "<expr>"`
# run arbitrary JavaScript with full filesystem and network access;
# the argv path gate cannot reason about the JS inside the string.
node = ["-e", "-p", "--eval", "--print"]

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv; same shape as `deny_args` above. Patterns that
# overlap `deny_args` are dead code (deny wins).
#
# [subprocess.requires_approval_args]
# git  = ["push"]
# npm  = ["install -g", "install --global"]
# pnpm = ["install -g"]
# yarn = ["global add"]

# Capabilities are auto-derived from the populated resource sections
# above. Populate [network].http_get_allow to enable net.http_get.

# Optional: declare a WebSearch tool with a routing hint. Bridges (the
# local-executor harness, IDE plugins, ...) read `backend_url` to tell
# the model where to make the search call instead of leaving it to
# guess. DuckDuckGo's Instant Answer API is the default — public,
# non-tracking, no auth required, returns JSON. Note: it returns
# abstracts/definitions for famous-entity queries, not full web search
# results. For broader coverage, swap for a self-hosted SearxNG,
# Brave Search, Tavily, etc. by changing the URL below and adding
# the new host to http_get_allow.
#
# [tools.WebSearch]
# capabilities   = ["net.http_get"]
# backend_url    = "https://api.duckduckgo.com/?format=json&no_html=1&skip_disambig=1&q="
# backend_method = "GET"
# description    = "DuckDuckGo Instant Answer API (public, non-tracking, JSON)."
#
# Then add to [network].http_get_allow above:
#   "api.duckduckgo.com",
"#;

const RUBY: &str = r#"# Denyx policy generated by `denyx init --lang ruby`.
#
# Inherits `secure-defaults` (system protection baseline). Adds Ruby /
# Rails toolchain allows, project source layout, explicit denies on
# staging/qa/production config files, and a deny on rails db:drop /
# db:reset (destructive Rails commands the preset does not cover).
#
# Default = minimal: `denyx init` strips the embedded `/tmp/**` write
# entry. Pass `--permissive` to keep it.

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "app/**",
    "config/**",
    "lib/**",
    "spec/**",
    "test/**",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    ".rubocop.yml",
    ".ruby-version",
    "config.ru",
    "README*",
]
write_allow = [
    "app/**",
    "lib/**",
    "spec/**",
    "test/**",
    "tmp/**",
    "log/**",
    "/tmp/**",
]
# Rails commonly stores secrets in encrypted form under config/. The
# preset blocks generic secrets paths; these add the Rails-specific
# conventions plus per-env config files.
deny = [
    "config/master.key",
    "config/credentials/*.key",
    "config/credentials/*.yml.enc",
    "config/credentials.yml.enc",
    "config/secrets.yml",
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/database.yml.production",
    "**/secrets.yml",
    "config/environments/production.rb",
    "config/environments/staging.rb",
]

[network]
# By default no host is reachable. Add hosts you actually need:
# http_get_allow = ["rubygems.org"]

[environment]
allow_vars = ["PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL", "GEM_HOME", "GEM_PATH", "BUNDLE_PATH"]
# RAILS_ENV is intentionally NOT in allow_vars here — production-like
# values should be set explicitly per-task, not read from the agent's
# inherited environment.

[subprocess]
allow_commands = [
    "ruby",
    "bundle", "bundler",
    "rake",
    "rails",
    "rspec",
    "rubocop", "standardrb",
    "git",
    "make",
]
# `secure-defaults` denies the ruby interpreter wholesale because
# `ruby -e "<code>"` runs arbitrary Ruby with full filesystem +
# network access — bypassing the argv path-gate (the path is
# constructed at runtime inside the inline string). The Ruby
# language template needs `ruby` to function, so we negate the
# deny — and accept the privilege grant. `bundle exec`, `rake`,
# `rails`, etc. ultimately run Ruby too, but they're project-bound
# (Rakefile, Gemfile) and not generic exec surfaces.
deny_commands = ["!ruby"]

[subprocess.deny_args]
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]
# Rails destructive db tasks. db:migrate is fine, db:drop / db:reset
# wipe the database.
rails = ["db:drop", "db:reset", "destroy"]
# Block bundle publish by default.
bundle = ["publish"]
gem = ["push"]
# Block inline-execution flags. `ruby -e "<code>"` runs arbitrary
# Ruby; the argv path-gate cannot reason about what the inline
# code will open. Force the agent to use real .rb files which DO
# go through fs.read/write gates.
ruby = ["-e", "-r"]

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv. Patterns that overlap `deny_args` are dead
# code (deny wins).
#
# [subprocess.requires_approval_args]
# git    = ["push"]
# gem    = ["install --user-install"]
# rails  = ["generate", "destroy"]
# bundle = ["update"]

# Capabilities are auto-derived from the populated resource sections
# above. Populate [network].http_get_allow to enable net.http_get.

# Optional: declare a WebSearch tool with a routing hint. Bridges (the
# local-executor harness, IDE plugins, ...) read `backend_url` to tell
# the model where to make the search call instead of leaving it to
# guess. DuckDuckGo's Instant Answer API is the default — public,
# non-tracking, no auth required, returns JSON. Note: it returns
# abstracts/definitions for famous-entity queries, not full web search
# results. For broader coverage, swap for a self-hosted SearxNG,
# Brave Search, Tavily, etc. by changing the URL below and adding
# the new host to http_get_allow.
#
# [tools.WebSearch]
# capabilities   = ["net.http_get"]
# backend_url    = "https://api.duckduckgo.com/?format=json&no_html=1&skip_disambig=1&q="
# backend_method = "GET"
# description    = "DuckDuckGo Instant Answer API (public, non-tracking, JSON)."
#
# Then add to [network].http_get_allow above:
#   "api.duckduckgo.com",
"#;

const RUST: &str = r#"# Denyx policy generated by `denyx init --lang rust`.
#
# Inherits `secure-defaults` (system protection baseline). Adds the
# cargo toolchain, typical project layout, and a deny on `cargo publish`
# (a network-effecting release operation that should be explicit).
#
# Default = minimal: `denyx init` strips the embedded `/tmp/**` write
# entry. Pass `--permissive` to keep it.

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "src/**",
    "tests/**",
    "benches/**",
    "examples/**",
    "crates/**",
    "Cargo.toml",
    "Cargo.lock",
    "rust-toolchain*",
    "rustfmt.toml",
    "clippy.toml",
    ".cargo/config*.toml",
    "README*",
]
write_allow = [
    "src/**",
    "tests/**",
    "benches/**",
    "examples/**",
    "crates/**",
    "target/**",
    "/tmp/**",
]
deny = [
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/production.toml",
    "**/staging.toml",
    "**/qa.toml",
    "**/secrets.toml",
]

[network]
# By default no host is reachable. Add hosts you actually need:
# http_get_allow = ["crates.io", "static.crates.io"]

[environment]
allow_vars = ["PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL", "CARGO_HOME", "RUSTUP_HOME"]

[subprocess]
allow_commands = [
    "cargo",
    "rustc",
    "rustfmt",
    "clippy-driver",
    "rust-analyzer",
    "git",
    "make",
]

[subprocess.deny_args]
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]
# `cargo publish` releases to crates.io. `cargo yank` pulls a release.
# Opt in explicitly per-project if your agent actually releases.
cargo = ["publish", "yank", "owner --remove"]

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv. Patterns that overlap `deny_args` are dead
# code (deny wins).
#
# [subprocess.requires_approval_args]
# git   = ["push"]
# cargo = ["install"]

# Capabilities are auto-derived from the populated resource sections
# above. Populate [network].http_get_allow to enable net.http_get.

# Optional: declare a WebSearch tool with a routing hint. Bridges (the
# local-executor harness, IDE plugins, ...) read `backend_url` to tell
# the model where to make the search call instead of leaving it to
# guess. DuckDuckGo's Instant Answer API is the default — public,
# non-tracking, no auth required, returns JSON. Note: it returns
# abstracts/definitions for famous-entity queries, not full web search
# results. For broader coverage, swap for a self-hosted SearxNG,
# Brave Search, Tavily, etc. by changing the URL below and adding
# the new host to http_get_allow.
#
# [tools.WebSearch]
# capabilities   = ["net.http_get"]
# backend_url    = "https://api.duckduckgo.com/?format=json&no_html=1&skip_disambig=1&q="
# backend_method = "GET"
# description    = "DuckDuckGo Instant Answer API (public, non-tracking, JSON)."
#
# Then add to [network].http_get_allow above:
#   "api.duckduckgo.com",
"#;

const GO: &str = r#"# Denyx policy generated by `denyx init --lang go`.
#
# Inherits `secure-defaults` (system protection baseline). Adds the Go
# toolchain and typical layout. Go's build/test commands rarely have
# destructive equivalents that the secure-defaults preset doesn't
# already cover.
#
# Default = minimal: `denyx init` strips the embedded `/tmp/**` write
# entry. Pass `--permissive` to keep it.

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "**/*.go",
    "go.mod",
    "go.sum",
    ".golangci.yml",
    ".golangci.yaml",
    "Makefile",
    "README*",
]
write_allow = [
    "**/*.go",
    "/tmp/**",
]
deny = [
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/production.yml",
    "**/production.yaml",
    "**/staging.yml",
    "**/staging.yaml",
    "**/qa.yml",
    "**/qa.yaml",
    "**/secrets.yml",
    "**/secrets.yaml",
]

[network]
# By default no host is reachable. `go mod download` needs proxy.golang.org
# and sum.golang.org if you want module fetches:
# http_get_allow = ["proxy.golang.org", "sum.golang.org"]

[environment]
allow_vars = ["PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL", "GOPATH", "GOROOT", "GOCACHE", "GOMODCACHE", "GO111MODULE"]

[subprocess]
allow_commands = [
    "go",
    "gofmt", "goimports",
    "golangci-lint",
    "delve", "dlv",
    "git",
    "make",
]

[subprocess.deny_args]
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv. Patterns that overlap `deny_args` are dead
# code (deny wins).
#
# [subprocess.requires_approval_args]
# git = ["push"]
# go  = ["install"]

# Capabilities are auto-derived from the populated resource sections
# above. Populate [network].http_get_allow to enable net.http_get.

# Optional: declare a WebSearch tool with a routing hint. Bridges (the
# local-executor harness, IDE plugins, ...) read `backend_url` to tell
# the model where to make the search call instead of leaving it to
# guess. DuckDuckGo's Instant Answer API is the default — public,
# non-tracking, no auth required, returns JSON. Note: it returns
# abstracts/definitions for famous-entity queries, not full web search
# results. For broader coverage, swap for a self-hosted SearxNG,
# Brave Search, Tavily, etc. by changing the URL below and adding
# the new host to http_get_allow.
#
# [tools.WebSearch]
# capabilities   = ["net.http_get"]
# backend_url    = "https://api.duckduckgo.com/?format=json&no_html=1&skip_disambig=1&q="
# backend_method = "GET"
# description    = "DuckDuckGo Instant Answer API (public, non-tracking, JSON)."
#
# Then add to [network].http_get_allow above:
#   "api.duckduckgo.com",
"#;

#[cfg(test)]
mod tests {
    use super::*;

    /// Every language template lists `/tmp/**` in write_allow. The
    /// generator is responsible for stripping it under the minimal
    /// default; the const itself must still contain it (the
    /// permissive path uses the const verbatim).
    const ALL_LANGS: &[Lang] = &[
        Lang::Python,
        Lang::Node,
        Lang::Ruby,
        Lang::Rust,
        Lang::Go,
        Lang::Java,
        Lang::Dotnet,
    ];

    #[test]
    fn templates_carry_tmp_glob_so_permissive_can_keep_it() {
        for &lang in ALL_LANGS {
            assert!(
                lang.template().contains("\"/tmp/**\""),
                "{} template should include /tmp/** so the permissive path keeps it",
                lang.name()
            );
        }
    }

    #[test]
    fn generate_minimal_strips_tmp_glob() {
        for &lang in ALL_LANGS {
            let out = generate(lang, false);
            assert!(
                !out.contains("\"/tmp/**\""),
                "{} minimal output must not contain /tmp/**",
                lang.name()
            );
        }
    }

    #[test]
    fn generate_permissive_keeps_tmp_glob() {
        for &lang in ALL_LANGS {
            let out = generate(lang, true);
            assert!(
                out.contains("\"/tmp/**\""),
                "{} permissive output should still include /tmp/**",
                lang.name()
            );
        }
    }

    #[test]
    fn generate_minimal_is_valid_toml() {
        // Stripping a list entry must not break TOML parsing. Each
        // language template's minimal form must still parse as a
        // PolicyFile.
        for &lang in ALL_LANGS {
            let body = generate(lang, false);
            denyx_policy::PolicyFile::from_toml_str(&body).unwrap_or_else(|e| {
                panic!(
                    "minimal {} policy must parse cleanly; error: {e}\n--- body ---\n{body}",
                    lang.name()
                )
            });
        }
    }

    #[test]
    fn generate_permissive_is_valid_toml() {
        for &lang in ALL_LANGS {
            let body = generate(lang, true);
            denyx_policy::PolicyFile::from_toml_str(&body).unwrap_or_else(|e| {
                panic!(
                    "permissive {} policy must parse cleanly; error: {e}",
                    lang.name()
                )
            });
        }
    }

    #[test]
    fn strip_permissive_writes_drops_lines_with_only_tmp_glob() {
        let src = r#"[filesystem]
write_allow = [
    "src/**",
    "/tmp/**",
    "build/**",
]
"#;
        let out = strip_permissive_writes(src);
        assert!(!out.contains("/tmp/**"));
        assert!(out.contains("\"src/**\""));
        assert!(out.contains("\"build/**\""));
    }

    #[test]
    fn strip_permissive_writes_leaves_unrelated_tmp_mentions() {
        // A line mentioning /tmp/** in a comment must not be stripped
        // — only list-item lines whose trimmed content is the bare
        // quoted string.
        let src = r#"# We used to allow "/tmp/**" but no longer.
[filesystem]
write_allow = ["src/**"]
"#;
        let out = strip_permissive_writes(src);
        assert!(out.contains("# We used to allow \"/tmp/**\""));
    }

    #[test]
    fn generate_minimal_keeps_other_write_entries() {
        // For each language, every write_allow entry OTHER than
        // /tmp/** must still be present in the minimal output. Guards
        // against the strip accidentally eating too much.
        let cases: &[(Lang, &[&str])] = &[
            (Lang::Python, &["src/**", "tests/**", "build/**"]),
            (Lang::Node, &["src/**", "lib/**", "dist/**"]),
            (Lang::Ruby, &["app/**", "lib/**", "tmp/**"]),
            (Lang::Rust, &["src/**", "tests/**", "target/**"]),
            (Lang::Go, &["**/*.go"]),
            (Lang::Java, &["src/**", "target/**", "build/**"]),
            (Lang::Dotnet, &["src/**", "**/bin/**", "**/obj/**"]),
        ];
        for (lang, expected) in cases {
            let body = generate(*lang, false);
            for needle in *expected {
                assert!(
                    body.contains(&format!("\"{needle}\"")),
                    "{lang:?} minimal should retain write entry {needle:?}"
                );
            }
        }
    }
}

const JAVA: &str = r#"# Denyx policy generated by `denyx init --lang java`.
#
# Inherits `secure-defaults`. Adds JVM toolchain coverage for both
# Maven and Gradle — most JVM projects use one or the other, but the
# allow-lists are forgiving so a project that mixes them (a Gradle
# top-level + an embedded Maven plugin build, say) still works.
# Operators on a single-build-system project can prune the other.
#
# Kotlin and Scala projects fit this template too: their toolchains
# build on the JVM, and `kotlin` / `scala` aliases route here.
#
# Default = minimal: `denyx init` strips the embedded `/tmp/**` write
# entry. Pass `--permissive` to keep it.

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "src/**",
    "test/**",
    "tests/**",
    # Maven
    "pom.xml",
    ".mvn/**",
    "mvnw",
    "mvnw.cmd",
    # Gradle
    "build.gradle",
    "build.gradle.kts",
    "settings.gradle",
    "settings.gradle.kts",
    "gradle.properties",
    "gradlew",
    "gradlew.bat",
    "gradle/**",
    # Kotlin
    "*.kt",
    "*.kts",
    # General
    "README*",
    ".java-version",
    ".sdkmanrc",
]
write_allow = [
    "src/**",
    "test/**",
    "tests/**",
    # Maven build output
    "target/**",
    # Gradle build output
    "build/**",
    ".gradle/**",
    "/tmp/**",
]
deny = [
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/application-production.yml",
    "**/application-production.yaml",
    "**/application-production.properties",
    "**/application-staging.yml",
    "**/application-staging.yaml",
    "**/application-prod.yml",
    "**/application-prod.yaml",
    "**/secrets.yml",
    "**/secrets.yaml",
    "**/secrets.properties",
]

[network]
# By default no host is reachable. Add hosts you actually need:
# http_get_allow = ["repo.maven.apache.org", "plugins.gradle.org", "services.gradle.org", "repo1.maven.org"]

[environment]
allow_vars = [
    "PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL",
    # JVM-side
    "JAVA_HOME", "JDK_HOME", "JRE_HOME",
    "M2_HOME", "MAVEN_HOME", "GRADLE_HOME", "GRADLE_USER_HOME",
    "KOTLIN_HOME",
    # JVM flags + tools
    "JAVA_OPTS", "MAVEN_OPTS", "GRADLE_OPTS",
]

[subprocess]
allow_commands = [
    # JVM runtime + compiler
    "java", "javac",
    # Build systems
    "mvn", "./mvnw", "mvnw",
    "gradle", "./gradlew", "gradlew",
    # Kotlin
    "kotlin", "kotlinc",
    # Scala (sbt is the common build, but project-specific; not added by default)
    "scala", "scalac",
    # Project tooling
    "git",
    "make",
]
# `secure-defaults` denies the `java` interpreter wholesale because
# `java -jar` and `java <ClassName>` execute arbitrary bytecode that
# bypasses the argv path-gate. The Java template needs `java` to
# function, so we negate the deny — and accept the privilege grant.
# `mvn`/`gradle` ultimately invoke `java` too, but they're project-
# bound (pom.xml / build.gradle) rather than generic exec surfaces.
deny_commands = ["!java"]

[subprocess.deny_args]
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]
# Maven deploy + release plugins push artefacts to a remote repository.
# Opt in per-project if your agent legitimately publishes.
mvn = ["deploy", "release:perform", "release:prepare"]
# Gradle publish targets do the same; opt in per-project.
gradle = ["publish", "publishToMavenCentral", "publishPlugins"]
# Block inline-execution flags on the JVM CLI. `java -jar <arbitrary.jar>`
# loads bytecode that does whatever it pleases, but the `.jar` argument
# is path-gated. Inline `-e` doesn't exist for `java`. The wholesale
# `!java` negation above is the privilege grant; no additional flag
# block is meaningful at the CLI layer.

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv. Patterns that overlap `deny_args` are dead
# code (deny wins).
#
# [subprocess.requires_approval_args]
# git    = ["push"]
# mvn    = ["clean install", "install"]
# gradle = ["clean", "build"]

# Capabilities are auto-derived from the populated resource sections
# above. Populate [network].http_get_allow to enable net.http_get.
"#;

const DOTNET: &str = r#"# Denyx policy generated by `denyx init --lang dotnet`.
#
# Inherits `secure-defaults`. Adds .NET toolchain coverage — `dotnet`
# CLI plus C# / F# / VB project files. Build output lands in `bin/`
# and `obj/` per project.
#
# Default = minimal: `denyx init` strips the embedded `/tmp/**` write
# entry. Pass `--permissive` to keep it.

inherits = "secure-defaults"

[filesystem]
read_allow = [
    "src/**",
    "test/**",
    "tests/**",
    "*.sln",
    "**/*.csproj",
    "**/*.fsproj",
    "**/*.vbproj",
    "**/Directory.Build.props",
    "**/Directory.Build.targets",
    "**/Directory.Packages.props",
    "global.json",
    "nuget.config",
    "NuGet.Config",
    "**/appsettings.json",
    "**/appsettings.Development.json",
    "README*",
]
write_allow = [
    "src/**",
    "test/**",
    "tests/**",
    "**/bin/**",
    "**/obj/**",
    "/tmp/**",
]
deny = [
    "**/.env.production",
    "**/.env.staging",
    "**/.env.qa",
    "**/appsettings.Production.json",
    "**/appsettings.Staging.json",
    "**/appsettings.Production.*.json",
    "**/secrets.json",
    # User-Secrets storage (per-user, but the agent shouldn't read
    # them — see `dotnet user-secrets` docs).
    "~/.microsoft/usersecrets/**",
    "%APPDATA%/Microsoft/UserSecrets/**",
]

[network]
# By default no host is reachable. Add hosts you actually need:
# http_get_allow = ["api.nuget.org", "www.nuget.org", "globalcdn.nuget.org"]

[environment]
allow_vars = [
    "PATH", "HOME", "USER", "LANG", "LC_ALL", "TERM", "SHELL",
    "DOTNET_ROOT", "DOTNET_CLI_TELEMETRY_OPTOUT",
    "NUGET_PACKAGES", "NUGET_HTTP_CACHE_PATH",
    # ASP.NET runtime env (commonly set to Development locally)
    "ASPNETCORE_ENVIRONMENT", "DOTNET_ENVIRONMENT",
]

[subprocess]
allow_commands = [
    # .NET CLI
    "dotnet",
    # Project tooling
    "git",
    "make",
]

[subprocess.deny_args]
git = [
    "push --force",
    "push -f",
    "push --force-with-lease",
    "reset --hard",
    "clean -fd",
    "clean -fx",
    "clean -fdx",
    "branch -D",
    "filter-branch",
    "rebase -i",
    "update-ref -d",
    "reflog expire",
]
# `dotnet nuget push` publishes to a registry; `dotnet user-secrets`
# reads/writes per-user secrets the agent shouldn't generally touch;
# `dotnet ef database update` mutates the database. Opt in per-project.
dotnet = [
    "nuget push",
    "user-secrets",
    "ef database update",
    "ef database drop",
    "workload install",
]

# Optional per-argv approval. Uncomment patterns you want the
# operator to eyeball before each call. Substring match against
# the joined argv. Patterns that overlap `deny_args` are dead
# code (deny wins).
#
# [subprocess.requires_approval_args]
# git    = ["push"]
# dotnet = ["tool install --global", "publish"]

# Capabilities are auto-derived from the populated resource sections
# above. Populate [network].http_get_allow to enable net.http_get.
"#;

#[cfg(test)]
mod alias_tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn java_aliases_resolve() {
        for s in ["java", "JAVA", "kotlin", "scala", "jvm", "maven", "gradle"] {
            assert_eq!(Lang::from_str(s).unwrap(), Lang::Java, "{s}");
        }
    }

    #[test]
    fn dotnet_aliases_resolve() {
        for s in ["dotnet", "DOTNET", "csharp", "cs", "fsharp", "fs", "vb"] {
            assert_eq!(Lang::from_str(s).unwrap(), Lang::Dotnet, "{s}");
        }
    }

    #[test]
    fn unknown_language_error_lists_supported_set() {
        let e = Lang::from_str("haskell").unwrap_err();
        // The error message advertises the supported set; the new
        // additions must be in it.
        assert!(e.contains("java"), "{e}");
        assert!(e.contains("dotnet"), "{e}");
    }
}
